(function(){
 const host=document.getElementById('content'),base='https://nixa-sisventas-default-rtdb.firebaseio.com/sv_catalogo_publico',cache=new Map();let idsPromise,view=0,query='',group=false,list=false;
 const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const href=k=>'catalogo.html?producto='+encodeURIComponent(k);
 const normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
 const photo=(p,hero=false)=>/^https:\/\//i.test(p.imagenUrl||'')?'<img src="'+esc(p.imagenUrl)+'" alt="'+esc(p.nombre)+'" '+(hero?'fetchpriority="high"':'loading="lazy"')+'>':'<span class="photo-empty">Imagen no disponible</span>';
 const usd=n=>window.SVPublicCurrency?window.SVPublicCurrency.money(n):'US$ '+Number(n).toLocaleString('es-AR',{minimumFractionDigits:2,maximumFractionDigits:2});
 const comparison=p=>{const reference=Number(p.referenciaMLUSD),sale=Number(p.precioUSD);if(!(reference>0&&sale>0&&Number.isFinite(reference)&&Number.isFinite(sale)))return '';const saving=Math.round((reference-sale)*100)/100;return '<div class="ml-comparison '+(saving>0?'ml-saving':'')+'"><span>Referencia Mercado Libre</span><strong>'+usd(reference)+'</strong>'+(saving>0?'<b>'+Math.floor(saving/reference*1000)/10+'% menos · Ahorrás '+usd(saving)+'</b>':saving===0?'<b>Mismo precio que la referencia</b>':'')+'<small>Referencia registrada · equivalente en '+(window.SVPublicCurrency?.code||'USD')+'</small></div>';};
 const price=p=>'<div class="public-price">'+(p.precioUSD>0?usd(p.precioUSD)+(Number(p.iva)>0?'<small>IVA incluido</small>':''):'Consultar precio')+'</div>'+comparison(p);

 async function read(path){const r=await fetch(base+path,{cache:'no-store',credentials:'omit',signal:AbortSignal.timeout(15000)});if([401,403,404].includes(r.status))return null;if(!r.ok)throw Error();return r.json();}
 async function fresh(k){const p=await read('/'+encodeURIComponent(k)+'.json');if(p)cache.set(k,p);else cache.delete(k);return p;}
 const product=k=>cache.has(k)?Promise.resolve(cache.get(k)):fresh(k);
 const ids=()=>idsPromise||(idsPromise=read('_index.json').then(v=>Object.keys(v||{})).catch(e=>{idsPromise=null;throw e;}));
 function detail(k,p){document.title=p.nombre+' · Catálogo';host.innerHTML='<article class="product"><div class="photo">'+photo(p,true)+'</div><div class="info"><span class="tag">'+esc(p.marca)+'</span><h1>'+esc(p.nombre)+'</h1>'+price(p)+'<button class="btn cart-primary" data-add="'+esc(k)+'" type="button">Agregar a mi lista</button><p>'+esc(p.descripcion)+'</p></div></article><nav class="navigation" aria-label="Productos"></nav>';}
 async function navigation(k,token){try{const keys=(await ids()).sort(),i=keys.indexOf(k);if(i<0||keys.length<2)return;async function neighbor(d){for(let n=1;n<keys.length;n++){const id=keys[(i+d*n+keys.length)%keys.length];if(await product(id))return id;}return null;}const [a,b]=await Promise.all([neighbor(-1),neighbor(1)]);if(token!==view)return;host.querySelector('nav').innerHTML=(a?'<a class="btn" href="'+href(a)+'">← Producto anterior</a>':'')+(b?'<a class="btn" href="'+href(b)+'">Producto siguiente →</a>':'');}catch(_){}}
 function renderGrid(){const grid=host.querySelector('.grid');if(!grid)return;grid.classList.toggle('list-view',list);const entries=[...cache].filter(([,p])=>normalize(p.nombre+' '+(p.marca||'')).includes(normalize(query))).sort((a,b)=>(group?(a[1].marca||'').localeCompare(b[1].marca||'','es'):0)||String(a[1].nombre||'').localeCompare(String(b[1].nombre||''),'es'));const count=host.querySelector('[data-count]');if(count)count.textContent=entries.length+' '+(entries.length===1?'producto':'productos');let last=null;grid.innerHTML=entries.map(([k,p])=>{const brand=p.marca||'Otras marcas';const heading=group&&brand!==last?'<h2 class="brand-group">'+esc(brand)+'</h2>':'';last=brand;return heading+'<article class="tile"><a class="tile-link" href="'+href(k)+'">'+photo(p)+'<div class="tile-info"><span class="tile-brand">'+esc(p.marca||'Catálogo')+'</span><h2>'+esc(p.nombre)+'</h2>'+price(p)+'<span class="tile-more">Ver producto <span aria-hidden="true">↗</span></span></div></a><button class="btn tile-add" data-add="'+esc(k)+'" type="button" aria-label="Agregar '+esc(p.nombre)+' a mi lista">+ Agregar a mi lista</button></article>';}).join('')|| (query?'<div class="empty-state"><h2>No encontramos ese producto</h2><p>Probá con otra palabra, modelo o marca.</p></div>':'');}
 async function show(){const token=++view,k=new URLSearchParams(location.search).get('producto');try{if(k){if(!cache.has(k))host.textContent='Cargando producto…';const p=await product(k);if(token!==view)return;if(!p){host.textContent='Este producto ya no está disponible en el catálogo.';return;}detail(k,p);void navigation(k,token);return;}
 document.title='Catálogo · SisVentas';host.innerHTML='<div class="catalog-heading"><div><span class="eyebrow">DESCUBRÍ NUESTROS PRODUCTOS</span><h1>Tu próximo favorito.</h1><p>Explorá marcas, compará opciones y encontrá lo que buscás.</p></div><span class="currency-note">Precios en <span data-currency-note>'+(window.SVPublicCurrency?.code||'USD')+'</span></span></div><div class="catalog-controls"><label><input type="checkbox" data-group '+(group?'checked':'')+'> Agrupar por marca</label><button class="btn" data-layout aria-pressed="'+list+'">'+(list?'Ver cuadrícula':'Ver lista')+'</button></div><input type="search" class="search" aria-label="Buscar producto" placeholder="Buscar por producto, modelo o marca…"><div class="catalog-meta"><span data-count>0 productos</span><p data-loading>Cargando productos…</p></div><div class="grid"></div>';host.querySelector('.search').value=query;host.querySelector('.search').oninput=e=>{query=e.target.value;renderGrid();};host.querySelector('[data-group]').onchange=e=>{group=e.target.checked;renderGrid();};host.querySelector('[data-layout]').onclick=e=>{list=!list;e.target.textContent=list?'Ver cuadrícula':'Ver lista';e.target.setAttribute('aria-pressed',String(list));renderGrid();};renderGrid();const keys=await ids();let cursor=0,failed=0;await Promise.all(Array.from({length:Math.min(6,keys.length)},async()=>{while(cursor<keys.length){const key=keys[cursor++];try{await product(key);if(token===view)renderGrid();}catch(_){failed++;}}}));if(token===view)host.querySelector('[data-loading]').textContent=failed?'Algunos productos no pudieron cargarse.':cache.size?'':'No hay productos para mostrar.';
 }catch(_){if(token===view)host.textContent='No se pudo cargar el catálogo. Revisá la conexión y recargá la página.';}}
 host.addEventListener('error',e=>{if(e.target.tagName==='IMG'){const fallback=document.createElement('span');fallback.className='photo-empty';fallback.textContent='Imagen no disponible';e.target.replaceWith(fallback);}},true);
 document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){const p=cache.get(add.dataset.add);if(p){window.SVPublicCart?.add(add.dataset.add,p);add.textContent='✓ Agregado ('+(window.SVPublicCart?.count(add.dataset.add)||1)+')';}return;}const a=e.target.closest('a');if(!a||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey||e.button)return;const u=new URL(a.href);if(u.origin===location.origin&&u.pathname===location.pathname){e.preventDefault();history.pushState({},'',u);show();window.scrollTo(0,0);}});window.addEventListener('catalog-currency-change',()=>{const k=new URLSearchParams(location.search).get('producto');if(k&&cache.has(k)){detail(k,cache.get(k));void navigation(k,view);}else{renderGrid();const note=host.querySelector('[data-currency-note]');if(note)note.textContent=window.SVPublicCurrency?.code||'USD';}});window.addEventListener('popstate',show);show();
})();
