(function(){
 const host=document.getElementById('content'),base='https://nixa-sisventas-default-rtdb.firebaseio.com/sv_catalogo_publico',cache=new Map();let idsPromise,view=0,query='',group=false,list=false;
 const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const href=k=>'catalogo.html?producto='+encodeURIComponent(k);
 const photo=(p,hero=false)=>/^https:\/\//i.test(p.imagenUrl||'')?'<img src="'+esc(p.imagenUrl)+'" alt="'+esc(p.nombre)+'" '+(hero?'fetchpriority="high"':'loading="lazy"')+'>':'<span>Imagen no disponible</span>';
 const price=p=>'<div class="public-price">'+(p.precioUSD>0?'US$ '+Number(p.precioUSD).toLocaleString('es-AR',{minimumFractionDigits:2,maximumFractionDigits:2})+'<small>Precio público · USD'+(Number(p.iva)>0?' · IVA incluido':'')+'</small>':'Consultar precio')+'</div>';
 async function read(path){const r=await fetch(base+path,{cache:'no-store',credentials:'omit',signal:AbortSignal.timeout(15000)});if([401,403,404].includes(r.status))return null;if(!r.ok)throw Error();return r.json();}
 async function fresh(k){const p=await read('/'+encodeURIComponent(k)+'.json');if(p)cache.set(k,p);else cache.delete(k);return p;}
 const product=k=>cache.has(k)?Promise.resolve(cache.get(k)):fresh(k);
 const ids=()=>idsPromise||(idsPromise=read('_index.json').then(v=>Object.keys(v||{})).catch(e=>{idsPromise=null;throw e;}));
 function detail(k,p){document.title=p.nombre+' · Catálogo';host.innerHTML='<article class="product"><div class="photo">'+photo(p,true)+'</div><div class="info"><span class="tag">'+esc(p.marca)+'</span><h1>'+esc(p.nombre)+'</h1>'+price(p)+'<p>'+esc(p.descripcion)+'</p></div></article><nav class="navigation" aria-label="Productos"></nav>';}
 async function navigation(k,token){try{const keys=(await ids()).sort(),i=keys.indexOf(k);if(i<0||keys.length<2)return;async function neighbor(d){for(let n=1;n<keys.length;n++){const id=keys[(i+d*n+keys.length)%keys.length];if(await product(id))return id;}return null;}const [a,b]=await Promise.all([neighbor(-1),neighbor(1)]);if(token!==view)return;host.querySelector('nav').innerHTML=(a?'<a class="btn" href="'+href(a)+'">← Producto anterior</a>':'')+(b?'<a class="btn" href="'+href(b)+'">Producto siguiente →</a>':'');}catch(_){}}
 function renderGrid(){const grid=host.querySelector('.grid');if(!grid)return;grid.classList.toggle('list-view',list);const entries=[...cache].filter(([,p])=>(p.nombre+' '+p.marca).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(group?(a[1].marca||'').localeCompare(b[1].marca||'','es'):0)||a[1].nombre.localeCompare(b[1].nombre,'es'));let last=null;grid.innerHTML=entries.map(([k,p])=>{const brand=p.marca||'Otras marcas';const heading=group&&brand!==last?'<h2 class="brand-group">'+esc(brand)+'</h2>':'';last=brand;return heading+'<a class="tile" href="'+href(k)+'">'+photo(p)+'<div class="tile-info"><h2>'+esc(p.nombre)+'</h2>'+price(p)+'</div></a>';}).join('');}
 async function show(){const token=++view,k=new URLSearchParams(location.search).get('producto');try{if(k){if(!cache.has(k))host.textContent='Cargando producto…';const p=await product(k);if(token!==view)return;if(!p){host.textContent='Este producto ya no está disponible en el catálogo.';return;}detail(k,p);void navigation(k,token);return;}
 document.title='Catálogo · SisVentas';host.innerHTML='<h1>Catálogo</h1><div class="catalog-controls"><label><input type="checkbox" data-group '+(group?'checked':'')+'> Agrupar por marca</label><button class="btn" data-layout aria-pressed="'+list+'">'+(list?'Ver cuadrícula':'Ver lista')+'</button></div><input class="search" aria-label="Buscar producto" placeholder="Buscar producto…"><p data-loading>Cargando productos…</p><div class="grid"></div>';host.querySelector('.search').value=query;host.querySelector('.search').oninput=e=>{query=e.target.value;renderGrid();};host.querySelector('[data-group]').onchange=e=>{group=e.target.checked;renderGrid();};host.querySelector('[data-layout]').onclick=e=>{list=!list;e.target.textContent=list?'Ver cuadrícula':'Ver lista';e.target.setAttribute('aria-pressed',String(list));renderGrid();};renderGrid();const keys=await ids();let cursor=0,failed=0;await Promise.all(Array.from({length:Math.min(6,keys.length)},async()=>{while(cursor<keys.length){const key=keys[cursor++];try{await product(key);if(token===view)renderGrid();}catch(_){failed++;}}}));if(token===view)host.querySelector('[data-loading]').textContent=failed?'Algunos productos no pudieron cargarse.':cache.size?'':'No hay productos para mostrar.';
 }catch(_){if(token===view)host.textContent='No se pudo cargar el catálogo. Revisá la conexión y recargá la página.';}}
 document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey||e.button)return;const u=new URL(a.href);if(u.origin===location.origin&&u.pathname===location.pathname){e.preventDefault();history.pushState({},'',u);show();window.scrollTo(0,0);}});window.addEventListener('popstate',show);show();
})();
