const fs=require('fs'),vm=require('vm'),test=require('node:test'),assert=require('node:assert/strict');
const src=fs.readFileSync('js/app.v3.7.8.js','utf8');
function setup(){const mov={tipo:'adelanto',empleadoId:'mauro',empleadoNombre:'Mauro',monto:200000,montoPagado:200000,estado:'pagado',gastoFbKey:'g1',pagos:{p1:{monto:200000}}};const g={fbKey:'g1',tipoPagable:'adelanto',empleadoId:'mauro',empleadoFbKey:'mauro',empleadoNombre:'Mauro',legacyKey:'ctaemp/mauro/m1',descripcion:'Adelanto — Mauro',monto:200000,montoPagado:200000,pagos:mov.pagos};const db={sisventas:{ctaemp:{mauro:{m1:mov},osmar:{}},gastos:{g1:g}}};let writes=0;const get=p=>p.split('/').reduce((o,k)=>o&&o[k],db)||null;const c={currentUser:'Admin',window:{fbDB:{},fbRef:(_,p='')=>p,fbGet:async p=>({val:()=>structuredClone(get(p))}),fbPush:()=>({key:'audit'}),fbUpdate:async(_,updates)=>{writes++;for(const [p,v]of Object.entries(updates)){const parts=p.split('/'),key=parts.pop();let target=db;for(const k of parts)target=target[k]||(target[k]={});if(v===null)delete target[key];else target[key]=structuredClone(v);}}}};vm.createContext(c);vm.runInContext(src.slice(src.indexOf('function _esGastoAdelanto('),src.indexOf('function guardarGastoCompleto()')),c);return {c,db,g,mov,get,writes:()=>writes};}
test('cambiar Mauro a Osmar mueve el movimiento y actualiza ambas identidades y descripción',async()=>{const x=setup();await x.c._guardarEdicionGastoAdelanto(x.g,'g1',{...x.g,empleadoId:'osmar',empleadoNombre:'Osmar',medio:'Efectivo',fecha:'2026-09-25'});assert.equal(x.get('sisventas/ctaemp/mauro/m1'),null);assert.equal(x.get('sisventas/ctaemp/osmar/m1').empleadoId,'osmar');assert.equal(x.g.empleadoFbKey,'osmar');assert.equal(x.g.legacyKey,'ctaemp/osmar/m1');assert.equal(x.g.descripcion,'Adelanto — Osmar');assert.equal(x.writes(),1);});
test('resuelve vínculo histórico aunque empleadoId haya cambiado',async()=>{const x=setup();x.g.empleadoId='osmar';x.g.empleadoFbKey='osmar';const refs=await x.c._movimientosVinculadosGasto(x.g,'g1');assert.equal(refs.length,1);assert.equal(refs[0].empKey,'mauro');});
test('eliminar después de anular retira cuenta original y gasto en una escritura auditada',async()=>{const x=setup();x.g.empleadoId='osmar';x.g.montoPagado=0;x.mov.montoPagado=0;await x.c._eliminarAdelantoGastoVinculado(x.g,'g1');assert.equal(x.get('sisventas/ctaemp/mauro/m1'),null);assert.equal(x.get('sisventas/gastos/g1'),null);assert.ok(x.get('sisventas/auditoria_pagos/audit'));assert.equal(x.writes(),1);});
test('no elimina un adelanto pagado o compensado',async()=>{const x=setup();await assert.rejects(x.c._eliminarAdelantoGastoVinculado(x.g,'g1'));x.g.montoPagado=0;x.mov.montoPagado=0;x.mov.montoCompensado=100;await assert.rejects(x.c._eliminarAdelantoGastoVinculado(x.g,'g1'));assert.equal(x.writes(),0);});
test('no sobrescribe destino existente ni reasigna compensados',async()=>{const x=setup();const datos={...x.g,empleadoId:'osmar',empleadoNombre:'Osmar'};x.db.sisventas.ctaemp.osmar.m1={tipo:'otro'};await assert.rejects(x.c._guardarEdicionGastoAdelanto(x.g,'g1',datos));delete x.db.sisventas.ctaemp.osmar.m1;x.mov.montoCompensado=100;await assert.rejects(x.c._guardarEdicionGastoAdelanto(x.g,'g1',datos));assert.equal(x.writes(),0);});
test('anular pago encuentra Mauro aunque el gasto diga Osmar y permite eliminar después',async()=>{
 const x=setup();x.g.empleadoId='osmar';x.g.empleadoFbKey='osmar';x.c.currentRole='admin';x.c._normalizarComprobantePagoGasto=()=>null;x.c._pagoGastoResumenSimulado=()=>({pagado:0,estado:'pendiente_pago',reembolsado:false,ultimo:{}});x.c._gastosPagosCache=null;x.c._gastosFechaImputacionCache=null;
 vm.runInContext(src.slice(src.indexOf('async function _persistirAjustePagoGasto('),src.indexOf('async function guardarEdicionPagoGasto(')),x.c);
 await x.c._persistirAjustePagoGasto(x.g,x.mov.pagos.p1,'p1',{estado:'anulado'},'anular_pago','error de empleado');assert.equal(x.get('sisventas/ctaemp/mauro/m1').montoPagado,0);assert.equal(x.get('sisventas/ctaemp/mauro/m1').pagos.p1.estado,'anulado');assert.equal(x.get('sisventas/ctaemp/mauro/m1').estado,'aprobado');await x.c._eliminarAdelantoGastoVinculado(x.g,'g1');assert.equal(x.get('sisventas/ctaemp/mauro/m1'),null);
});

