const fs=require('fs');
const assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
const source=fs.readFileSync('js/modules/resizable-tables.js','utf8');
assert.doesNotMatch(html,/Columnas %<\/button>/,'Columnas debe mostrarse sólo como icono');
assert.doesNotMatch(html,/data-sv-no-resize="1"/,'las grillas principales no deben excluir el arrastre');
const resize=source.slice(source.indexOf('function resizedPercentages'),source.indexOf('function applySavedPercentProfile'));
assert.doesNotMatch(resize,/next\[neighborIndex\]\s*=/,'redimensionar no debe achicar la columna vecina');
assert.match(source,/function applyLivePixelWidth\(deltaPx\)/,'el arrastre debe trabajar en píxeles como una grilla de escritorio');
assert.match(source,/startRenderedTotal \+ deltaReal/,'el ancho total debe crecer y desplazar las columnas siguientes');
assert.match(source,/savePercentages\(table, \{\}\)/,'el arrastre en píxeles debe desactivar el perfil porcentual anterior');
assert.match(source,/saveWidths\(table, finalWidths\)/,'el mouse debe guardar los anchos físicos finales');
assert.match(source,/wrap\.clientWidth[^\n]*paddingHorizontal/,'el 100% debe usar el ancho útil visible sin contar padding');
assert.match(source,/Object\.keys\(pixelProfile\)\.length \? percentagesFromRenderedLayout\(table\)/,'el editor debe reflejar el tamaño arrastrado');
assert.match(source,/root\.querySelectorAll\('table'\)/,'todas las grillas deben entrar al escaneo global');
assert.doesNotMatch(source,/base\[neighbor\]\s*=/,'restablecer una columna tampoco debe modificar la vecina');
assert.match(source,/function autoWidthForColumn\(table, index\)/,'debe medir el contenido más ancho de la columna');
assert.match(source,/context\.measureText\(text\)\.width/,'el autoajuste debe medir el texto y no el ancho forzado de la celda');
assert.match(source,/persistPixelLayout\(table, index, autoWidthForColumn\(table, index\)\)/,'el doble clic debe autoajustar sólo esa columna');
assert.match(source,/sv-pixel-table/,'el modo manual debe impedir que min-width redistribuya las demás columnas');
assert.match(source,/Doble clic para ajustar al contenido/,'la ayuda debe describir el autoajuste real');
assert.doesNotMatch(source,/Arrastr\?/,'la ayuda no debe contener caracteres dañados');
assert.match(source,/btn-icon admin-only sv-column-percent-btn/);
assert.match(source,/dragUsesPercent = false/,
  'El arrastre manual debe pasar a píxeles para no recalcular las demás columnas');
console.log('columnas-redimension-windows.test.js OK');
