const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const approval=require('../js/modules/commercial-approval.js');
const config={descuentoLimite:10,montoLimite:600000};
const original={items:[{cod:'P-11250',qty:1,punit:96480,disc:0},{cod:'P-4108',qty:1,punit:10033.41,disc:0}],descuentoGeneral:20,subtotal:106513.41,total:106513.41,iva:0,conIva:false};
const discounted=()=>({...original,...approval.recalculateSale(original)});
const authorized=record=>({...record,autorizacionDescuento:approval.stamp(record,'venta',{usuario:'Admin',uid:'admin'},config)});
test('SP-37710: resolver soporte mantiene el 20%, los centavos y el total de la venta',()=>{const result=discounted();assert.equal(result.subtotal,85210.73);assert.equal(result.descuento,21302.68);assert.equal(result.total,85210.73);assert.match(approval.status(original,'venta',config).reason,/no coincide/);assert.equal(approval.status(authorized(result),'venta',config).blocked,false);});
test('no se confunde guardar un porcentaje con autorizarlo',()=>{assert.equal(approval.status(discounted(),'venta',config).needsApproval,true);assert.equal(approval.status({...discounted(),margenAutorizadoPorAdmin:true},'venta',config).blocked,true);});
test('descuento por ítem y combinación con general requieren aprobación',()=>{const r={items:[{qty:1,punit:100,disc:20}],descuentoGeneral:0,total:80,iva:0,conIva:false};assert.equal(approval.status(r,'venta',config).blocked,true);assert.ok(approval.discount({...r,descuentoGeneral:6,items:[{qty:1,punit:100,disc:6}]},'venta').maximum>10);});
test('autorización pierde vigencia si cambian los importes',()=>{const r=authorized(discounted());assert.equal(approval.status({...r,total:80000},'venta',config).blocked,true);const changed={...r,items:r.items.map(i=>({...i,punit:i.punit+100}))};Object.assign(changed,approval.recalculateSale(changed));assert.equal(approval.status(changed,'venta',config).blocked,true);});
test('presupuestos en revisión no salen aunque el usuario sea admin; aprobaciones anteriores explícitas se conservan',()=>{const r={...discounted(),estado:'revision',requiereAprobacion:true,aprobadoPor:'Admin',aprobadoEn:'2026-09-10'};assert.equal(approval.status(r,'presupuesto',config).blocked,true);assert.equal(approval.status({...r,estado:'aprobado_int',requiereAprobacion:false},'presupuesto',config).blocked,false);assert.equal(approval.status({...r,estado:'aprobado_int',requiereAprobacion:false,vistaPreviaSinGuardar:true},'presupuesto',config).blocked,true);});
test('cero, límite exacto y descuentos inválidos',()=>{for(const d of [0,10]){const r={...original,descuentoGeneral:d};Object.assign(r,approval.recalculateSale(r));assert.equal(approval.status(r,'venta',config).blocked,false);}for(const d of [-1,101,Infinity])assert.equal(approval.status({...original,descuentoGeneral:d},'venta',config).blocked,true);});
function browser(role,confirm=true){const notices=[],ctx={document:{},APROBACION_CONFIG:config,currentUser:'Persona',currentUserUid:role,tienePermiso:()=>role==='admin',notify:m=>notices.push(m),svConfirm:async()=>confirm,escapeHTML:x=>x};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync('js/modules/commercial-approval.js','utf8'),ctx);return {ctx,notices};}
test('usuario sin permiso no autoriza y cancelar no registra aprobación',async()=>{for(const [role,confirm] of [['vendedor',true],['admin',false]]){const {ctx}=browser(role,confirm),r=discounted();assert.equal(await ctx.svAutorizarDescuentoVenta(r,null),false);assert.equal(r.autorizacionDescuento,null);}});
test('admin autoriza de forma explícita y queda auditado; una edición idéntica conserva la autorización',async()=>{const {ctx}=browser('admin'),r=discounted();assert.equal(await ctx.svAutorizarDescuentoVenta(r,null),true);assert.match(r.audit[0].accion,/Descuento autorizado/);assert.equal(ctx.svValidarSalidaComercial(r,'venta'),true);const {ctx:employee}=browser('vendedor');assert.equal(await employee.svAutorizarDescuentoVenta(discounted(),r),true);});
test('impresión y PDF bloqueados sin aprobación incluso para admin; factura oficial ya emitida conserva reimpresión',()=>{const {ctx}=browser('admin');assert.equal(ctx.svValidarSalidaComercial(discounted(),'venta'),false);assert.equal(ctx.svValidarSalidaComercial({...discounted(),factura:{cae:'123'}},'venta'),true);});
const index=fs.readFileSync('index.html','utf8');const active=index.match(/src="\.\/js\/(app\.v[^"?]+\.js)/)[1];const app=fs.readFileSync('js/'+active,'utf8');
function section(name,next){return app.slice(app.indexOf(name),app.indexOf(next,app.indexOf(name)+name.length));}
test('guardas conectadas antes de abrir impresión o compartir y antes de guardar',()=>{assert.ok(index.indexOf('commercial-approval.js')<index.indexOf(active));for(const [name,next,guard] of [['function imprimirVentaActual','function ',"svValidarSalidaComercial(v,'venta')"],['function pdfYWhatsappVenta','var _comprobanteConImagen',"svValidarSalidaComercial(v,'venta')"],['function pptoEnviarCliente','function pptoAccionPermitida',"svValidarSalidaComercial(p,'presupuesto')"],['async function imprimirPresupuesto(pptoRef','function urlImagenCapturable',"svValidarSalidaComercial(pptoGuardado,'presupuesto')"]]){const code=section(name,next);assert.ok(code.includes(guard),name);if(code.includes('window.open'))assert.ok(code.indexOf(guard)<code.indexOf('window.open'),name);}const save=section('async function confirmarVenta()','function ');assert.ok(app.includes('await svAutorizarDescuentoVenta(nuevaVenta,ventaOriginalEditar)'));assert.ok(app.includes('svAvisoAprobacionVenta(v)'));});
test('soporte respeta ventas que ya tienen descuento; el cálculo común se usa al resolver',()=>{const code=section('function spVentaTieneDefinicionComercial','async function spCerrarReclamo');const ctx={_svMontoPagadoVenta:()=>0};vm.createContext(ctx);vm.runInContext(code,ctx);assert.equal(ctx.spVentaTieneDefinicionComercial(original),true);assert.ok(section('async function spConfirmarResolucionVisita','function _pagableAplicarPagoLegacy').includes('SVCommercialApproval.recalculateSale(venta,items)'));});
test('fallo al persistir aprobación no deja el presupuesto aprobado en memoria',async()=>{const record={...discounted(),fbKey:'budget',estado:'revision',requiereAprobacion:true};let rendered=0;const ctx={pptoActualId:'budget',buscarPptoPorRef:()=>record,pptoAccionPermitidaParaRol:()=>true,svValidarSalidaComercial:()=>true,currentUser:'Admin',currentUserUid:'admin',currentRole:'admin',APROBACION_CONFIG:config,SVCommercialApproval:approval,svConfirm:async()=>true,notify:()=>{},window:{fbDB:{},fbUpdate:()=>{}},pptoPersistirActualizar:async()=>{throw Error('sin conexión');},verPpto:()=>rendered++};vm.createContext(ctx);vm.runInContext(section('async function pptoAccion(accion, opts)','function _redondearPrecioActual'),ctx);await ctx.pptoAccion('aprobar',{});assert.equal(record.estado,'revision');assert.equal(record.requiereAprobacion,true);assert.equal(record.autorizacionDescuento,undefined);assert.equal(rendered,0);});
test('el editor de venta exige guardar antes de imprimir y no reutiliza el detalle de otra operación',()=>{assert.match(section('function abrirModalImprimir(context','function otFirmaUrl'),/context==='venta'.*Guardá y autorizá/);});

test('venta histórica hereda aprobación sólo de un presupuesto vinculado e importes idénticos',()=>{
 const {ctx}=browser('admin'),sale=discounted();
 const budget={...sale,estado:'convertido',aprobadoPor:'Supervisora',aprobadoEn:'2026-09-30'};
 ctx._presupuestosOrigenDeVenta=()=>[budget];
 ctx.pptoDatosParaVenta=()=>({items:sale.items,descuentoPct:sale.descuentoGeneral,total:sale.total,iva:sale.iva,conIva:sale.conIva});
 assert.equal(ctx.svValidarSalidaComercial(sale,'venta'),true);
 assert.equal(ctx.svAvisoAprobacionVenta(sale),'');
 assert.equal(sale.autorizacionDescuento,undefined);
 const changed={...sale,items:sale.items.map(i=>({...i,punit:i.punit+1}))};Object.assign(changed,approval.recalculateSale(changed));
 assert.equal(ctx.svValidarSalidaComercial(changed,'venta'),false);
 budget.estado='revision';assert.equal(ctx.svValidarSalidaComercial(sale,'venta'),false);
 budget.estado='convertido';ctx._presupuestosOrigenDeVenta=()=>[budget,budget];assert.equal(ctx.svValidarSalidaComercial(sale,'venta'),false);
 ctx._presupuestosOrigenDeVenta=()=>[];assert.equal(ctx.svValidarSalidaComercial(sale,'venta'),false);
});
