const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const src=fs.readFileSync('js/modules/purchase-orders.js','utf8');
function context(){const c={window:{obtenerCostoItemVenta:i=>i.costoTotalCompra??i.qty*i.costoUnitarioCompra,_rentIngresoNetoVenta:s=>s.subtotal},materialListLocked:l=>!!l.compraConfirmacion||(l.ordenesIds||[]).length>0,balanceFinalizado:l=>l.estado==='cancelada',providersFor:p=>p?.providers||[]};vm.createContext(c);vm.runInContext(src.slice(src.indexOf('  function cancelExteriorPreparation('),src.indexOf('  window.ocEliminarPreparacionExterior=')),c);return c;}
const fixture=()=>({productos:{P:{codWeb:'local',providers:[{nombre:'Local',proveedorKey:'L',url:'local',costo:80,disponible:true,exterior:false}]}},ventas:{S:{subtotal:500,items:[{cod:'P',qty:2,origenCompra:'Exterior',costoUnitarioCompra:40,costoUnitarioAntesPreparacion:100}]}},listas_materiales:{A:{estado:'preparacion',ventaFbKey:'S',items:[{codigo:'P',productoKey:'P',linea:0,cantidadNecesaria:2}],simuladorParaguay:{version:6,rows:[{agreed:40}]}}}});
test('eliminar devuelve costos y proveedor local, conserva comisiones e historial',()=>{const d=fixture();context().cancelExteriorPreparation(d,'A','Admin',123);assert.equal(d.ventas.S.costoTotal,160);assert.equal(d.ventas.S.items[0].proveedorCompra,'Local');assert.equal(d.ventas.S.items[0].origenCompra,'Local');assert.equal(d.ventas.S.items[0].costoUnitarioAntesPreparacion,100);assert.equal(d.ventas.S.subtotal,500);assert.equal(d.listas_materiales.A.estado,'cancelada');assert.equal(d.listas_materiales.A.simuladorParaguay,undefined);assert.equal(d.listas_materiales.A.preparacionExteriorEliminada.simulador.version,6);assert.equal(d.ventas.S.audit.length,1);});
test('sin proveedor local u órdenes existentes no se confirma la cancelación',()=>{const d=fixture();d.productos.P.providers=[];assert.throws(()=>context().cancelExteriorPreparation(d,'A','Admin',123),/falta un proveedor local/);const e=fixture();e.ordenes={O:{listaMaterialesId:'A'}};assert.throws(()=>context().cancelExteriorPreparation(e,'A','Admin',123),/órdenes/);});
test('conjunta cancela hijos y devuelve todas las ventas; stock conserva extras en historial',()=>{const d=fixture();d.listas_materiales.A.compraConjuntaId='J';d.listas_materiales.J={estado:'preparacion',origen:'conjunta',sources:[{listId:'A',ventaFbKey:'S'}],simuladorParaguay:{extras:[{code:'X'}]}};context().cancelExteriorPreparation(d,'J','Admin',123);assert.equal(d.listas_materiales.A.compraConjuntaId,undefined);assert.equal(d.listas_materiales.J.estado,'cancelada');assert.equal(d.listas_materiales.J.preparacionExteriorEliminada.simulador.extras[0].code,'X');const stock={listas_materiales:{T:{origen:'stock_paraguay',estado:'preparacion',simuladorParaguay:{extras:[{code:'X'}]}}}};context().cancelExteriorPreparation(stock,'T','Admin',123);assert.equal(stock.listas_materiales.T.estado,'cancelada');});

test('eliminación condicional no muta el intento y conserva conflicto real',async()=>{
 for(const concurrent of [false,true]){
  const c=context(),data=fixture();let committed=false,notice='';
  Object.assign(c,{state:{lists:[{fbKey:'A'}]},balancePurchaseTitle:()=> 'Prueba',renderBalanceCompra:()=>{}});
  Object.assign(c.window,{currentUserUid:'u',currentUser:'Admin',permisoModulo:()=>true,fbDB:{},fbRef:()=>'',SVGuardedWrites:{...require('../js/core/guarded-writes')},fbGet:async()=>({val:()=>data}),svConfirm:async()=>true,notify:t=>{notice=t;},fbRunTransaction:async(_r,fn)=>{const current=structuredClone(data);if(concurrent)current.listas_materiales.A.estado='ordenada';const next=fn(current);assert.equal(current.ventas.S.items[0].origenCompra,'Exterior');committed=true;assert.equal(next.ventas.S.items[0].origenCompra,'Local');return{committed:true};}});
  c.window.SVGuardedWrites.restTransaction=c.window.fbRunTransaction;
  const start=src.indexOf('  window.ocEliminarPreparacionExterior=');vm.runInContext(src.slice(start,src.indexOf('  function balanceTieneCompraExterior',start)),c);
  await c.window.ocEliminarPreparacionExterior('A');assert.equal(committed,!concurrent);assert.match(notice,concurrent?/Otro usuario/:/Preparación eliminada/);
 }
});
