const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const appPath=fs.readFileSync('index.html','utf8').match(/src="\.\/(js\/app\.v[0-9.]+\.js)"/)[1];
const source=fs.readFileSync(appPath,'utf8');
function fn(name,next){return source.slice(source.indexOf(name),source.indexOf(next,source.indexOf(name)));}
function env(){const calls=[];const context={window:{SVParaguayPortal:{isProductSheetOpen:()=>true,returnFromProduct:()=>{calls.push('ofertas');return true;}},svBloquearSalidaCotizacion:()=>false},_cotizacionProductoActiva:false,_proveedoresEnFicha:false,_pfFirmaNavegacion:'original',firmaNavegacionEditorProducto:()=> 'original',cancelarCotizacionProductoEditor:()=>calls.push('cancelar-consulta'),restaurarProveedoresEnFicha:()=>calls.push('restaurar-proveedores'),svConfirm:async()=>false,notify:()=>{},_hide:()=>{throw Error('No debe navegar al módulo Productos');}};vm.createContext(context);vm.runInContext(fn('async function cerrarFormProducto(guardado)', 'function cambiarMonedaProducto'),context);return {context,calls};}
test('guardar y volver al catálogo omiten todos los retornos anteriores',async()=>{for(const saved of [true,false]){const {context,calls}=env();context.window._retornoEdicionProductoPpto=true;await context.cerrarFormProducto(saved);assert.deepEqual(calls,['cancelar-consulta','ofertas']);}});
test('cancelar salida con cambios mantiene la ficha abierta',async()=>{const {context,calls}=env();context.firmaNavegacionEditorProducto=()=> 'modificado';await context.cerrarFormProducto();assert.deepEqual(calls,[]);});
test('cotización activa bloquea salida antes de regresar',async()=>{const {context,calls}=env();context._cotizacionProductoActiva=true;assert.equal(await context.cerrarFormProducto(),false);assert.deepEqual(calls,[]);});
test('restaura controles de proveedores antes de volver',async()=>{const {context,calls}=env();context._proveedoresEnFicha=true;await context.cerrarFormProducto(true);assert.deepEqual(calls,['cancelar-consulta','restaurar-proveedores','ofertas']);});
test('volver desde ficha omite enlaces a otras pantallas',()=>{const {context,calls}=env();vm.runInContext(fn('function cerrarDetalleProducto()', 'function editarDesdeDetalle'),context);context.cerrarDetalleProducto();assert.deepEqual(calls,['ofertas']);});
test('la ficha abierta bloquea navegación entre módulos',()=>{const {context}=env();vm.runInContext(fn('function showPage(id, el)', '\nfunction '),context);assert.equal(context.showPage('dashboard'),false);});
