const test=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const {webcrypto}=require('node:crypto');const fs=require('node:fs');const app=require('./helpers/active-app').readActiveApp().source;const code=app.slice(app.indexOf('function _gastoIdentidad('),app.indexOf('function guardarGastoRapido('));
function client(db,fail=false){const ctx={TextEncoder,Uint8Array,Set,window:{crypto:webcrypto,fbDB:{},fbRef:(_,p)=>p,fbGet:async()=>({val:()=>structuredClone(db)}),fbRunTransaction:async(p,fn)=>{if(fail)throw Error('Sin conexión');const key=p.split('/').at(-1),next=fn(db[key]||null);if(next===undefined)return {committed:false};db[key]=structuredClone(next);return {committed:true};}}};vm.createContext(ctx);vm.runInContext(code,ctx);return ctx;}
const gasto={fecha:'2026-09-30',descripcion:'Uber oficina a Ciardi',monto:4890,tipo:'Variable',categoria:'Transporte',empleadoId:'e1005',medio:'Efectivo'};
test('rechaza el mismo gasto histórico aunque cambien hora, usuario o estado',async()=>{const db={viejo:{...gasto,ts:1,estado:'pagado'}};await assert.rejects(client(db)._crearGastoSinDuplicar({...gasto,ts:2,usuario:'otro'}),/Ya existe/);assert.equal(Object.keys(db).length,1);});
test('doble clic guarda una sola vez',async()=>{const db={},c=client(db);const r=await Promise.allSettled([c._crearGastoSinDuplicar(gasto),c._crearGastoSinDuplicar(gasto)]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal(Object.keys(db).length,1);});
test('dos equipos simultáneos no duplican',async()=>{const db={};const r=await Promise.allSettled([client(db)._crearGastoSinDuplicar(gasto),client(db)._crearGastoSinDuplicar(gasto)]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal(Object.keys(db).length,1);});
test('admite otro importe, fecha o descripción',async()=>{const db={},c=client(db);for(const g of [gasto,{...gasto,monto:5744},{...gasto,fecha:'2026-10-01'},{...gasto,descripcion:'Uber de regreso'}])await c._crearGastoSinDuplicar(g);assert.equal(Object.keys(db).length,4);});
test('un fallo libera la protección local para reintentar',async()=>{const db={},c=client(db,true);await assert.rejects(c._crearGastoSinDuplicar(gasto),/Sin conexión/);c.window.fbRunTransaction=client(db).window.fbRunTransaction;await c._crearGastoSinDuplicar(gasto);assert.equal(Object.keys(db).length,1);});
test('las tres altas manuales usan la protección',()=>{assert.equal((app.match(/_crearGastoSinDuplicar\(datos\)/g)||[]).length,4);assert.ok(!app.includes("fbPush(window.fbRef(window.fbDB, 'sisventas/gastos'), datos)"));});
