const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const source=fs.readFileSync('js/core/guarded-writes.js','utf8');
function setup(fetch){const user={uid:'u',getIdToken:async()=> 'test-token'},root={currentUserUid:'u',fbAuth:{currentUser:user},fetch};const c={window:root,URL,AbortSignal,TextEncoder};vm.createContext(c);vm.runInContext(source,c);return root;}
const response=(data,etag='v1',status=200)=>({ok:status>=200&&status<300,status,headers:{get:()=>etag},json:async()=>structuredClone(data)});
test('REST condicional rechaza carrera y recalcula conservando cambios ajenos',async()=>{let writes=0,reads=0;const root=setup(async(url,opts)=>{assert.equal(new URL(url).searchParams.get('auth'),'test-token');if(!opts.method){reads++;assert.equal(opts.headers['X-Firebase-ETag'],'true');return response({preparacion:1,ajeno:reads},'v'+reads);}writes++;assert.equal(new URL(url).searchParams.has('print'),false);assert.equal(opts.headers['if-match'],'v'+writes);assert.equal(JSON.parse(opts.body).ajeno,writes);assert.equal(JSON.parse(opts.body).preparacion,2);return response(null,null,writes===1?412:204);});assert.equal((await root.SVGuardedWrites.restTransaction('https://test.firebaseio.com/sisventas',d=>({...d,preparacion:2}))).committed,true);assert.equal(writes,2);});
test('sin ETag o cambio de sesión no escribe; fallas de red no reintentan a ciegas',async()=>{for(const mode of ['etag','session','network']){let writes=0;let root;root=setup(async(url,opts)=>{if(!opts.method){if(mode==='session')root.currentUserUid='otro';return response({a:1},mode==='etag'?null:'v1');}writes++;throw Error('disconnect');});await assert.rejects(root.SVGuardedWrites.restTransaction('https://test.firebaseio.com/sisventas',d=>({...d,a:2})));assert.equal(writes,mode==='network'?1:0);assert.match(root.SVGuardedWrites.errorMessage(Error('disconnect')),/No se pudo confirmar/);}});
test('escrituras mayores a 16 MB van por REST con precondición, sin SDK',async()=>{const large='x'.repeat(17*1024*1024);let written=0;const root=setup(async(url,opts)=>{if(!opts.method)return response({imagen:large,lista:1});written=opts.body.length;assert.equal(opts.headers['if-match'],'v1');return response(null,null,204);});assert.equal((await root.SVGuardedWrites.restTransaction('https://test.firebaseio.com/sisventas',d=>({...d,lista:2}))).committed,true);assert.ok(written>16*1024*1024);});

test('guardar con caché vacía verifica servidor y conserva conflicto real o eliminación',async()=>{for(const current of [{nombre:'Lista'}, {nombre:'Cambio ajeno'}, null]){let writes=0;const root=setup(async(url,opts)=>{if(!opts.method)return response(current);writes++;return response(JSON.parse(opts.body));});root.fbDB={};root.fbRef=()=> 'https://test.firebaseio.com/lista';root.fbGet=async()=>({val:()=>current});root.fbRunTransaction=async(ref,update)=>{assert.equal(update(null),undefined);return {committed:false};};const save=root.SVGuardedWrites.save('lista',{nombre:'Lista'},{nombre:'Editada'},true);if(current?.nombre==='Lista'){assert.equal((await save).nombre,'Editada');assert.equal(writes,1);}else{await assert.rejects(save,{code:'SV_CONFLICT'});assert.equal(writes,0);}}});
test('listas toleran fecha automática resuelta pero rechazan cambios de contenido',async()=>{for(const changed of [false,true]){const current={nombre:changed?'Ajena':'Lista',actualizadoEn:200};const root=setup(async()=>{throw Error('No debe necesitar REST');});root.fbDB={};root.fbRef=()=> 'https://test.firebaseio.com/lista';root.fbGet=async()=>({val:()=>current});root.fbRunTransaction=async(ref,update)=>{const next=update(current);return {committed:next!==undefined,snapshot:{val:()=>next}};};const result=root.SVGuardedWrites.save('sv_listas_paraguay/u/lista',{nombre:'Lista',actualizadoEn:199},{nombre:'Lista',actualizadoEn:300},true,{ignoreUpdatedTimestamp:true});if(changed)await assert.rejects(result,{code:'SV_CONFLICT'});else assert.equal((await result).actualizadoEn,300);}});