const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function setup(request){const events={},label={textContent:''},cart={hidden:true,setAttribute(){},querySelector(){return label}};const document={visibilityState:'visible',addEventListener(n,f){(events[n]??=[]).push(f)},createElement(){return cart},body:{appendChild(){}}};const window={navigator:request?{wakeLock:{request}}:{}};vm.runInNewContext(fs.readFileSync('js/core/loading-indicator.js','utf8'),{window,document,Map,Set,Promise,setTimeout,requestAnimationFrame:f=>f()});return {api:window.SisVentas.carga,document,cart,label,emit:n=>(events[n]||[]).forEach(f=>f())};}
const flush=()=>new Promise(r=>setImmediate(r));
function lock(){return {releases:0,addEventListener(n,f){this.onrelease=f},async release(){this.releases++;this.onrelease?.()}};}
test('mensajes independientes, actualizables y limpieza al cerrar sesión',()=>{const s=setup(),a=s.api.mostrar('Cargando'),b=s.api.mostrar('Guardando');assert.equal(s.label.textContent,'Guardando');b.actualizar('Generando PDF');assert.equal(s.label.textContent,'Generando PDF');b();assert.equal(s.label.textContent,'Cargando');a();assert.equal(s.cart.hidden,true);s.api.mostrar('Guardando',{persistirAlNavegar:true});s.emit('sisventas:session-ended');assert.equal(s.cart.hidden,true);});
test('bloqueo compartido, regreso a pestaña y liberación final',async()=>{const locks=[];const s=setup(async()=>{const l=lock();locks.push(l);return l});const a=s.api.mantenerPantallaActiva(),b=s.api.mantenerPantallaActiva();await flush();assert.equal(locks.length,1);a();assert.equal(locks[0].releases,0);s.document.visibilityState='hidden';s.emit('visibilitychange');await flush();assert.equal(locks[0].releases,1);s.document.visibilityState='visible';s.emit('visibilitychange');await flush();assert.equal(locks.length,2);b();await flush();assert.equal(locks[1].releases,1);});
test('libera solicitud tardía después de finalizar y tolera falta de soporte',async()=>{let resolve;const s=setup(()=>new Promise(r=>resolve=r)),end=s.api.mantenerPantallaActiva();end();const l=lock();resolve(l);await flush();assert.equal(l.releases,1);setup().api.mantenerPantallaActiva()();const denied=setup(async()=>{throw Error('denied')});denied.api.mantenerPantallaActiva()();await flush();});
test('sesión terminada libera pantalla y error en tarea cierra cartel',async()=>{const l=lock(),s=setup(async()=>l);s.api.mantenerPantallaActiva();await flush();s.emit('sisventas:session-ended');await flush();assert.equal(l.releases,1);await assert.rejects(s.api.ejecutar('Guardando',async()=>{throw Error('falló')}));assert.equal(s.cart.hidden,true);});
const {load}=require('./helpers/app-functions.cjs');
test('actualizador libera pantalla al terminar o fallar, incluso por excepción',async()=>{for(const fail of [false,true]){let releases=0;const modal={dataset:{}};const ctx={document:{getElementById:()=>modal},window:{SisVentas:{carga:{mantenerPantallaActiva:()=>()=>{releases++}}}},_svCargaOperacion_ejecutarActualizadorMasivoBiosegur:async()=>{if(fail)throw Error('falló');return 'ok'}};load(ctx,['ejecutarActualizadorMasivoBiosegur']);if(fail)await assert.rejects(ctx.ejecutarActualizadorMasivoBiosegur());else assert.equal(await ctx.ejecutarActualizadorMasivoBiosegur(),'ok');assert.equal(releases,1);assert.equal(modal._liberarPantalla,null);}});
test('cancelación libera inmediatamente sin esperar la respuesta del servidor',async()=>{let releases=0,resolve;const modal={dataset:{},_liberarPantalla:null};const ctx={document:{getElementById:id=>id==='modal-actualizador-precios'?modal:null},window:{SisVentas:{carga:{mantenerPantallaActiva:()=>()=>{releases++}}}},svConfirm:async()=>true,mostrarResultadosActualizador(){},_svCargaOperacion_ejecutarActualizadorMasivoBiosegur:()=>{modal.dataset.ejecutando='1';return new Promise(r=>resolve=r)}};load(ctx,['ejecutarActualizadorMasivoBiosegur','detenerActualizadorMasivoPrecios']);const running=ctx.ejecutarActualizadorMasivoBiosegur();await ctx.detenerActualizadorMasivoPrecios();assert.equal(releases,1);assert.equal(modal._detenerSolicitado,true);resolve();await running;});
