const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const src=fs.readFileSync(require('path').join(__dirname,'../js/modules/purchase-orders.js'),'utf8');const clone=x=>JSON.parse(JSON.stringify(x));const db={};let failSale=false;
const ctx={console,Date,Math,Promise,Number,Object,String,Array,JSON,PATH_ORDERS:'orders',PATH_LISTS:'lists',state:{orders:[]},today:()=> '2026-09-27',safeKey:x=>String(x),document:{getElementById:()=>({style:{}})},window:{fbDB:{},currentUser:'test',fbRef:(_,p)=>p,notify:()=>{},fbRunTransaction:async(path,fn)=>{if(failSale&&path.includes('ventas')){failSale=false;throw Error('fallo simulado');}const result=fn(clone(db[path]??null));if(result===undefined)return {committed:false};db[path]=clone(result);return {committed:true,snapshot:{val:()=>clone(result)}};}},transactionInventory:async(key,fn)=>{const value=clone(db['inv/'+key]||{});fn(value);db['inv/'+key]=value;},update:async(path,value)=>{db[path]=Object.assign(db[path]||{},clone(value));}};vm.createContext(ctx);
vm.runInContext(src.slice(src.indexOf('  function buildPlannedOrders'),src.indexOf('  async function confirmPlannedPurchase')),ctx);
vm.runInContext(src.slice(src.indexOf('  function syncSalePurchaseCosts'),src.indexOf('  function ',src.indexOf('  function syncSalePurchaseCosts')+12)),ctx);
ctx.renderBalanceCompra=()=>{};vm.runInContext(src.slice(src.indexOf('  async function finishPlannedPurchase'),src.indexOf('  function generateOrdersFromList')),ctx);
vm.runInContext(src.slice(src.indexOf('  async function finishReceipt'),src.indexOf('  function openManualOrder')),ctx);

const {calculate}=require('../js/modules/paraguay-planner.js');
const parameters={usd:1000,usdt:1000,bus:101.01,allocation:'value',shippingMode:'insured',shippingInsuredUSD:0};
const rows=[{key:'P1|A:0|PY',sourceListId:'A',productKey:'P1',providerKey:'PY',provider:'PY',code:'P1',qty:1,usd:10,include:true,existing:1},{key:'P1|B:0|PY',sourceListId:'B',productKey:'P1',providerKey:'PY',provider:'PY',code:'P1',qty:2,usd:10,include:true,existing:1,expenseExcluded:true}];
const result=calculate(parameters,rows);assert.deepEqual(result.onsiteAllocation,[101.01,0]);assert.equal(result.onsite,30101.01);
const sources=[{listId:'A',ventaId:'VA',ventaFbKey:'SA',cliente:'Cliente'},{listId:'B',ventaId:'VB',ventaFbKey:'SB',cliente:'Cliente'}];
const sim={complete:true,chosen:'onsite',parameters,result,rows,extras:[{productKey:'P1',providerKey:'PY',provider:'PY',code:'P1',qty:1,usd:10}]};
const list={fbKey:'CJ',numero:'CJ',origen:'conjunta',sources,simuladorParaguay:sim,items:rows.map(r=>({sourceListId:r.sourceListId,productoKey:r.productKey,codigo:r.code,linea:r.sourceListId+':0',proveedorKey:'PY',cantidadNecesaria:r.qty+r.existing,incluir:true}))};
const orders=ctx.buildPlannedOrders(list,sim);assert.equal(orders.length,3);assert.equal(orders.find(o=>o.ventaFbKey==='SA').total,10101.01);assert.equal(orders.find(o=>o.ventaFbKey==='SB').total,20000);assert.equal(orders.find(o=>!o.ventaFbKey).total,10000);assert.equal(new Set(orders.map(o=>o.fbKey)).size,3);assert.ok(orders.every(o=>o.listaMaterialesId==='CJ'));
(async()=>{db['inv/P1']={general:2,enCompra:0,reservado:0};const confirmation={estado:'pendiente',ordenes:orders};await ctx.finishPlannedPurchase(clone(list),confirmation);assert.equal(db['inv/P1'].general,0);assert.equal(db['inv/P1'].reservado,2);assert.equal(db['inv/P1'].enCompra,4);assert.equal(db['inv/P1'].asignaciones.SA.reservado,1);assert.equal(db['inv/P1'].asignaciones.SB.reservado,1);confirmation.estado='pendiente';await ctx.finishPlannedPurchase(clone(list),confirmation);assert.equal(db['inv/P1'].reservado,2);assert.equal(db['inv/P1'].enCompra,4);assert.ok(!db['lists/CJ_A']);assert.ok(!db['lists/CJ_B']);assert.equal(db['sisventas/ventas/SA'].ordenesCompraIds.length,1);assert.equal(db['sisventas/ventas/SB'].ordenesCompraIds.length,1);
for(const sale of ['SA','SB'])db['sisventas/ventas/'+sale].items=[{codigo:'P1',qty:sale==='SA'?1:2,costoUnitarioCompra:10000}];
const order=orders.find(o=>o.ventaFbKey==='SB'),current=clone(db['orders/'+order.fbKey]);await ctx.finishReceipt(current,[{index:0,item:current.items[0],qty:1,costoUnitarioReal:9000,proveedor:'PY',proveedorKey:'PY'}]);assert.equal(db['inv/P1'].asignaciones.SA.reservado,1);assert.equal(db['inv/P1'].asignaciones.SB.reservado,2);assert.equal(db['inv/P1'].enCompra,3);assert.equal(db['orders/'+order.fbKey].estado,'recepcion_parcial');assert.equal(db['sisventas/ventas/SB'].items[0].costoRealCompraAcumulado,9000);assert.equal(db['sisventas/ventas/SA'].items[0].costoRealCompraAcumulado,undefined);console.log('OK: compra conjunta, gasto único, exclusión sin residuo, órdenes por destino, reserva por venta, reintentos y recepción parcial sin cruces.');})().catch(e=>{console.error(e);process.exitCode=1});
