const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const src=fs.readFileSync(require('path').join(__dirname,'../js/modules/purchase-orders.js'),'utf8');const clone=x=>JSON.parse(JSON.stringify(x));const db={};let failSale=false;
const ctx={console,Date,Math,Promise,Number,Object,String,Array,JSON,PATH_ORDERS:'orders',PATH_LISTS:'lists',state:{orders:[]},today:()=> '2026-09-27',safeKey:x=>String(x),document:{getElementById:()=>({style:{}})},window:{fbDB:{},currentUser:'test',fbRef:(_,p)=>p,notify:()=>{},fbRunTransaction:async(path,fn)=>{if(failSale&&path.includes('ventas')){failSale=false;throw Error('fallo simulado');}const result=fn(clone(db[path]??null));if(result===undefined)return {committed:false};db[path]=clone(result);return {committed:true,snapshot:{val:()=>clone(result)}};}},transactionInventory:async(key,fn)=>{const value=clone(db['inv/'+key]||{});fn(value);db['inv/'+key]=value;},update:async(path,value)=>{db[path]=Object.assign(db[path]||{},clone(value));}};vm.createContext(ctx);vm.runInContext(src.slice(src.indexOf('  function orderProviderSummary('),src.indexOf('  function purchaseDifferenceLabel(')),ctx);
vm.runInContext(src.slice(src.indexOf('  function buildPlannedOrders'),src.indexOf('  async function confirmPlannedPurchase')),ctx);
vm.runInContext(src.slice(src.indexOf('  function syncSalePurchaseCosts'),src.indexOf('  function ',src.indexOf('  function syncSalePurchaseCosts')+12)),ctx);
ctx.renderBalanceCompra=()=>{};vm.runInContext(src.slice(src.indexOf('  async function finishPlannedPurchase'),src.indexOf('  function generateOrdersFromList')),ctx);
vm.runInContext(src.slice(src.indexOf('  async function finishReceipt'),src.indexOf('  function openManualOrder')),ctx);
const list={fbKey:'L1',numero:'LM1',ventaId:'V1',ventaFbKey:'S1',items:[{productoKey:'P1',codigo:'P1',linea:0,proveedorKey:'PY',incluir:true,cantidadComprar:2}]};const sim={complete:true,chosen:'remote',parameters:{usd:1000,usdt:1100,extraLogisticsUSD:10},result:{remoteAllocation:[2000]},rows:[{key:'P1|0|PY',include:true,qty:2,usd:10,code:'P1',description:'Venta',provider:'Proveedor'}],extras:[{productKey:'P1',code:'P1',description:'Extra del mismo producto',provider:'Proveedor',providerKey:'PY',qty:3,usd:8}]};const orders=ctx.buildPlannedOrders(list,sim);assert.equal(orders.length,2);const sale=orders.find(x=>x.origen==='venta'),extra=orders.find(x=>x.origen==='extra_stock');assert.equal(sale.items[0].costoUnitario,11000);assert.equal(extra.ventaFbKey,'');assert.equal(sale.total,22000);assert.equal(extra.total,36400);assert.throws(()=>ctx.buildPlannedOrders({...list,items:[]},sim),/selección/);
(async()=>{db['orders/O1']={...clone(extra),fbKey:'O1',generacionPendiente:false,items:[{productoKey:'P1',codigo:'P1',descripcion:'Extra',cantidadOrdenada:3,cantidadRecibida:0,costoUnitario:100}]};db['inv/P1']={general:0,reservado:0,enCompra:3};const movement={index:0,item:clone(db['orders/O1'].items[0]),qty:2,costoUnitarioReal:90,proveedor:'PY',proveedorKey:'PY'};await ctx.finishReceipt(clone(db['orders/O1']),[movement]);assert.equal(db['inv/P1'].general,2);assert.equal(db['orders/O1'].estado,'recepcion_parcial');await assert.rejects(()=>ctx.finishReceipt({...clone(db['orders/O1']),recepciones:[]},[movement]),/cambió/);assert.equal(db['inv/P1'].general,2);
 db['orders/O2']={...clone(sale),fbKey:'O2',generacionPendiente:false,items:[{productoKey:'P2',codigo:'P2',descripcion:'Venta',cantidadOrdenada:1,cantidadRecibida:0,costoUnitario:100}]};db['sisventas/ventas/S1']={items:[{codigo:'P2',qty:1,costoUnitario:100,costoUnitarioCompra:100}],total:200};const m={index:0,item:clone(db['orders/O2'].items[0]),qty:1,costoUnitarioReal:80,proveedor:'PY',proveedorKey:'PY'};failSale=true;await assert.rejects(()=>ctx.finishReceipt(clone(db['orders/O2']),[m]),/simulado/);assert.equal(db['inv/P2'].reservado,1);await ctx.finishReceipt(clone(db['orders/O2']),[]);assert.equal(db['inv/P2'].reservado,1);assert.equal(db['orders/O2'].recepciones.length,1);assert.equal(db['sisventas/ventas/S1'].items[0].costoRealCompraAcumulado,80);assert.equal(db['inv/P1'].general,2);const before=Number(db['inv/P1'].enCompra||0),confirmation={estado:'pendiente',ordenes:orders};await ctx.finishPlannedPurchase(clone(list),confirmation);assert.equal(db['inv/P1'].enCompra,before+5);confirmation.estado='pendiente';await ctx.finishPlannedPurchase(clone(list),confirmation);assert.equal(db['inv/P1'].enCompra,before+5);assert.equal(db['orders/'+sale.fbKey].generacionPendiente,false);console.log('OK: confirmación reintentable, destinos separados, precio negociado, extras sin margen de venta, recepción parcial, cliente desactualizado y reintento tras fallo sin duplicar stock ni costo.');})().catch(e=>{console.error(e);process.exitCode=1});
