const fs=require('fs');
const index=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('css/v3-preview.css','utf8');
const js=fs.readFileSync('js/modules/v3-visual-preview.js','utf8');
if(!index.includes("p==='v3'")) throw new Error('La vista v3 debe activarse inicialmente por parámetro explícito');
if(!index.includes("sessionStorage.setItem('sisventas_visual_preview','v3')")) throw new Error('La vista v3 debe sobrevivir al cierre de sesión dentro de la misma pestaña');
if(!index.includes('css/v3-preview.css')) throw new Error('Falta cargar el estilo de vista previa');
if(!index.includes('js/modules/v3-visual-preview.js')) throw new Error('Falta cargar el comportamiento de vista previa');
if(!css.includes('html.sv-v3-preview .sidebar')) throw new Error('Falta rediseño de barra lateral');
if(!css.includes('html.sv-v3-preview #page-dashboard .metric')) throw new Error('Falta rediseño del inicio');
if(!css.includes('html.sv-v3-preview .login-box')) throw new Error('Falta rediseño del acceso');
if(!css.includes('html.sv-v3-preview body.dark-mode')) throw new Error('Falta la variante oscura propia de SisVentas 3');
if(!css.includes('color-scheme:light') || !css.includes('color-scheme:dark')) throw new Error('El estilo nuevo debe soportar modo claro y oscuro');
if(!index.includes("aplicarEstiloVisual('classic')") || !index.includes("aplicarEstiloVisual('v3')")) throw new Error('Configuración debe permitir alternar entre Clásico y SisVentas 3');
if(/html\.sv-v3-preview \.sidebar\s*\{[^}]*\bwidth\s*:/s.test(css)) throw new Error('La vista v3 no debe desplazar el contenido cambiando el ancho lateral');
if(/html\.sv-v3-preview \.topbar\s*\{[^}]*\bheight\s*:/s.test(css)) throw new Error('La vista v3 no debe cambiar la altura de la barra superior');
if(/html\.sv-v3-preview #page-dashboard \.metric\s*\{[^}]*\bpadding\s*:/s.test(css)) throw new Error('La vista v3 no debe alterar la geometría de los KPI');
if(!js.includes("pill.textContent='V3'")) throw new Error('Novedades debe distinguir el lanzamiento mayor');
console.log('OK vista previa v3 aislada y reversible');
