/* Relevamientos de campo: borrador por usuario, configuración técnica y adjuntos por ítem. */
(function(){
  'use strict';
  const schemas={
    alarma:{name:'Alarma',icon:'shield-check',hint:'Central, zonas y dispositivos',fields:[['tecnologia','Tecnología','choice',['Cableada','Inalámbrica','Mixta']],['central','Central propuesta','product','central'],['comunicador','Comunicador','product','comunicador'],['zonas','Zonas necesarias','number'],['magneticos','Magnéticos','number'],['pir','Sensores infrarrojos interiores','number'],['exterior','Sensores exteriores','number'],['sirenas','Sirenas','number'],['teclados','Teclados','number']]},
    camaras:{name:'Cámaras',icon:'device-cctv',hint:'Cobertura y tipo de instalación',fields:[['conexion','Conexión','choice',['Cableada','Wi-Fi','Mixta']],['armado','Armado','choice',['Kit','Equipos separados']],['tecnologia','Sistema','choice',['IP','TVI / analógico','A definir']],['domo','Cámaras domo','number'],['bullet','Cámaras bullet','number'],['ptz','Cámaras PTZ','number'],['grabador','Grabador propuesto','product','grabador'],['almacenamiento','Días de grabación requeridos','number'],['recorrido','Recorrido del cable y alimentación','text']]},
    video:{name:'Videoportero',icon:'device-landline-phone',hint:'Accesos, monitores y cerradura',fields:[['sistema','Sistema','choice',['IP','Dos hilos','A definir']],['frentes','Frentes de calle','number'],['monitores','Monitores interiores','number'],['apertura','Apertura de puerta','choice',['Sí','No','A definir']],['recorrido','Recorrido y alimentación','text']]},
    acceso:{name:'Control de acceso',icon:'lock',hint:'Puertas y formas de ingreso',fields:[['puertas','Puertas o accesos','number'],['metodo','Método de ingreso','choice',['Tarjeta','Huella','Rostro','PIN','Combinado']],['cerradura','Cerradura y tipo de puerta','text'],['usuarios','Usuarios estimados','number']]},
    redes:{name:'Redes / Wi-Fi',icon:'router',hint:'Puntos de red y cobertura',fields:[['puntos','Puntos de red','number'],['aps','Puntos Wi-Fi','number'],['internet','Internet existente','choice',['Sí','No','A verificar']],['recorrido','Cobertura, recorridos y gabinete','text']]},
    otro:{name:'Otro servicio',icon:'tools',hint:'Necesidad especial del cliente',fields:[['necesidad','Servicio y alcance solicitado','text']]}
  };
  const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  function products(kind,data){
    const re={central:/\bcentral\b|\b(panel|placa)\b.*(garnet|alonso|pc[- ]|alarma)|kit alarma|hub.*inalambrico/,comunicador:/\bcomunicador\b|\bip-500/,grabador:/\bnvr\b|\bdvr\b/}[kind];
    return Object.entries(data||{}).filter(([,p])=>{
      if(!p||p.activo===false||p.eliminado)return false;
      const name=norm(p.nombre||p.descripcion),cat=norm(p.categoria);
      if(/instalacion|configuracion|mano de obra/.test(cat+' '+name)||!re.test(name))return false;
      if(kind==='central'&&/gabinete para|fuente|sirena|expansor|receptor|comunicador 4g/.test(name))return false;
      if(kind==='comunicador'&&/panel|kit alarma/.test(name))return false;
      if(kind==='grabador'&&/disco|fuente|soporte|accesorio|balun/.test(name))return false;
      return true;
    }).map(([key,p])=>({key,name:p.nombre||p.descripcion||p.codigo}));
  }
  function validation(d){if(!d.cliente.trim())return 'Completá el cliente o contacto.';if(!d.direccion.trim())return 'Completá la dirección del relevamiento.';if(!d.services.length)return 'Elegí al menos un servicio.';for(const s of d.services)for(const f of schemas[s].fields){const v=(d.items[s+'.'+f[0]]||{}).value;if(f[2]==='number'&&v!==undefined&&v!==''&&(!Number.isInteger(Number(v))||Number(v)<0||Number(v)>9999))return 'Revisá la cantidad de '+f[1]+'.';}return '';}
  if(typeof module!=='undefined'&&module.exports){module.exports={schemas,products,validation};return;}
  const root=()=>document.getElementById('page-relevamientos');
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let draft=null,step=0,busy=false,dbPromise,saveQueue=Promise.resolve(),loadedOwner='',statusTimer;
  const owner=()=>String(window.currentUserEmail||window.currentUser||'');
  function fresh(){return {id:'REL-'+crypto.randomUUID(),cliente:'',direccion:'',contacto:'',services:[],items:{},createdAt:new Date().toISOString(),autor:window.currentUser||'',owner:owner()};}
  function db(){return dbPromise||(dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('sv-relevamientos',1);r.onupgradeneeded=()=>r.result.createObjectStore('drafts');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);}));}
  async function local(value){const database=await db();return new Promise((resolve,reject)=>{const tx=database.transaction('drafts',value===undefined?'readonly':'readwrite'),store=tx.objectStore('drafts'),r=value===undefined?store.get(owner()):value===null?store.delete(owner()):store.put(value,owner());tx.oncomplete=()=>resolve(r.result);tx.onerror=()=>reject(tx.error);});}
  function persist(){if(!draft||busy)return;const copy=JSON.parse(JSON.stringify(draft));saveQueue=saveQueue.then(()=>local(copy)).then(()=>{const n=document.getElementById('rel-draft-status');if(n)n.textContent='Borrador guardado en este dispositivo';}).catch(()=>{const n=document.getElementById('rel-draft-status');if(n)n.textContent='No se pudo guardar el borrador. No cierres esta ventana.';});}
  function field(s,f){const key=s+'.'+f[0],item=draft.items[key]||{},v=item.value??'';let control='';
    if(f[2]==='choice')control='<div class="rel-options">'+f[3].map(x=>'<button type="button" data-choice="'+esc(key)+'" data-value="'+esc(x)+'" aria-pressed="'+(v===x)+'">'+esc(x)+'</button>').join('')+'</div>';
    else if(f[2]==='number')control='<div class="rel-stepper"><button data-delta="-1" data-key="'+key+'" aria-label="Restar '+esc(f[1])+'">−</button><input aria-label="'+esc(f[1])+'" data-value-field="'+key+'" type="number" min="0" max="9999" step="1" inputmode="numeric" value="'+esc(v)+'" placeholder="—"><button data-delta="1" data-key="'+key+'" aria-label="Sumar '+esc(f[1])+'">+</button></div>';
    else if(f[2]==='product'){const opts=products(f[3],window.prodData);control='<select aria-label="'+esc(f[1])+'" data-value-field="'+key+'"><option value="">Seleccionar producto</option><option value="A definir" '+(v==='A definir'?'selected':'')+'>A definir en oficina</option><option value="No requiere" '+(v==='No requiere'?'selected':'')+'>No requiere</option>'+opts.map(p=>'<option value="'+esc(p.key)+'" '+(p.key===v?'selected':'')+'>'+esc(p.name)+'</option>').join('')+'</select>';if(!opts.length)control+='<small>Sin productos compatibles cargados. Podés dejarlo a definir.</small>';}
    else control='<textarea data-value-field="'+key+'" aria-label="'+esc(f[1])+'" placeholder="Describí lo que encontraste…">'+esc(v)+'</textarea>';
    return '<article class="rel-field"><h3>'+esc(f[1])+'</h3>'+control+'<details '+(item.note||item.photo?'open':'')+'><summary><i class="ti ti-camera"></i> Foto y observaciones'+(item.photo?' · 1 foto':'')+'</summary><textarea data-note="'+key+'" aria-label="Observaciones de '+esc(f[1])+'" placeholder="Ubicación, dificultad o detalle importante…">'+esc(item.note||'')+'</textarea><div class="rel-photo-actions"><label class="btn"><i class="ti ti-camera"></i> Cámara<input type="file" accept="image/*" capture="environment" data-photo="'+key+'" hidden></label><label class="btn"><i class="ti ti-photo"></i> Galería<input type="file" accept="image/*" data-photo="'+key+'" hidden></label></div>'+(item.photo?'<img class="rel-photo" src="'+esc(item.photo.data)+'" alt="Foto de '+esc(f[1])+'"><button class="btn" data-remove-photo="'+key+'">Quitar foto</button>':'')+'</details></article>';
  }
  function summary(d){return d.services.map(s=>'<section class="rel-summary"><h3>'+esc(schemas[s].name)+'</h3>'+schemas[s].fields.map(f=>{const item=d.items[s+'.'+f[0]]||{};let v=item.label||item.value;return '<div><strong>'+esc(f[1])+'</strong><span>'+esc(v===undefined||v===''?'Sin relevar':v)+'</span>'+(item.note?'<p>'+esc(item.note)+'</p>':'')+(item.photo?'<img class="rel-photo" src="'+esc(item.photo.data)+'" alt="'+esc(f[1])+'">':'')+'</div>';}).join('')+'</section>').join('');}
  function render(){if(!root()||!draft)return;const steps=['Lugar','Servicios','Relevar','Resumen'];root().innerHTML='<div class="rel-shell"><header class="rel-heading"><div><span class="rel-eyebrow">TRABAJO EN CAMPO</span><h1>Relevamientos</h1><p>De la visita a una propuesta bien definida.</p></div><button class="btn" data-list>Ver guardados</button></header><nav class="rel-steps">'+steps.map((x,i)=>'<button data-step="'+i+'" aria-current="'+(step===i?'step':'false')+'"><b>'+ (i+1)+'</b>'+x+'</button>').join('')+'</nav><div id="rel-content">'+(step===0?'<section class="rel-place"><h2>¿Dónde vamos a trabajar?</h2><label>Cliente o contacto<input data-meta="cliente" value="'+esc(draft.cliente)+'" placeholder="Nombre del cliente"></label><label>Dirección / sector<input data-meta="direccion" value="'+esc(draft.direccion)+'" placeholder="Calle, número y sector"></label><label>Teléfono o contacto en el lugar<input data-meta="contacto" value="'+esc(draft.contacto)+'" placeholder="Opcional"></label></section>':step===1?'<h2>¿Qué necesita el cliente?</h2><p class="rel-muted">Podés seleccionar varios servicios.</p><div class="rel-services">'+Object.entries(schemas).map(([s,c])=>'<button data-service="'+s+'" aria-pressed="'+draft.services.includes(s)+'"><i class="ti ti-'+c.icon+'"></i><strong>'+c.name+'</strong><span>'+c.hint+'</span><b>'+ (draft.services.includes(s)?'Seleccionado':'Agregar')+'</b></button>').join('')+'</div>':step===2?(draft.services.length?draft.services.map(s=>'<section class="rel-service-section"><h2><i class="ti ti-'+schemas[s].icon+'"></i> '+schemas[s].name+'</h2><div class="rel-fields">'+schemas[s].fields.map(f=>field(s,f)).join('')+'</div></section>').join(''):'<p>Seleccioná primero los servicios que vas a relevar.</p>'):'<h2>'+esc(draft.cliente||'Sin cliente')+'</h2><p>'+esc(draft.direccion||'Sin dirección')+'</p><p class="rel-muted">Los campos sin completar quedan como “Sin relevar”; no se interpretan como cero.</p>'+summary(draft))+'</div><footer class="rel-footer"><span id="rel-draft-status">Borrador local · se guarda automáticamente</span><div><button class="btn" data-back '+(step===0?'disabled':'')+'>Anterior</button><button class="btn btn-primary" '+(step===3?'data-save':'data-next')+'>'+(step===3?'Guardar relevamiento':'Continuar')+' <i class="ti ti-arrow-right"></i></button></div></footer></div>';}
  async function open(){if(!window.permisoModulo('relevamientos'))return;try{if(!draft||loadedOwner!==owner()){draft=await local()||fresh();loadedOwner=owner();step=0;}render();if(typeof window.fbCargarProductos==='function')Promise.resolve(window.fbCargarProductos()).catch(()=>{});}catch(e){root().innerHTML='<div class="card">No se pudo abrir el borrador: '+esc(e.message)+'</div>';}}
  async function save(){const error=validation(draft);if(error){window.notify(error);return;}if(!window.fbDB||!navigator.onLine){window.notify('Sin conexión. El borrador queda en este dispositivo.');return;}busy=true;renderBusy(true);try{await saveQueue;const data=JSON.parse(JSON.stringify(draft));data.items=Object.fromEntries(Object.entries(data.items).filter(([key])=>data.services.includes(key.split('.')[0])));data.savedAt=new Date().toISOString();await window.fbSet(window.fbRef(window.fbDB,'sisventas/relevamientos/'+data.id),data);await local(null);draft=null;window.notify('Relevamiento guardado');await list();}catch(e){window.notify('No se pudo guardar: '+e.message+'. El borrador se conserva.');}finally{busy=false;renderBusy(false);}}
  function renderBusy(value){root().querySelectorAll('button,input,textarea,select').forEach(n=>n.disabled=value);const b=root().querySelector('[data-save]');if(b)b.textContent=value?'Guardando…':'Guardar relevamiento';}
  async function list(){root().innerHTML='<div class="rel-shell"><p role="status">Cargando relevamientos…</p></div>';try{const snap=await window.fbGet(window.fbRef(window.fbDB,'sisventas/relevamientos'));const all=Object.values(snap.val()||{}).sort((a,b)=>String(b.savedAt).localeCompare(String(a.savedAt)));root().innerHTML='<div class="rel-shell"><header class="rel-heading"><h1>Relevamientos guardados</h1><button class="btn btn-primary" data-resume>'+ (draft?'Volver al borrador':'Nuevo relevamiento')+'</button></header><div class="rel-saved">'+(all.map(d=>'<details class="rel-summary"><summary><strong>'+esc(d.cliente)+'</strong><span>'+esc(d.direccion)+' · '+esc(new Date(d.savedAt).toLocaleDateString('es-AR'))+'</span></summary><p>'+esc(d.id)+' · '+esc(d.autor)+'</p>'+summary(d)+'</details>').join('')||'<p>Todavía no hay relevamientos guardados.</p>')+'</div></div>';}catch(e){root().innerHTML='<div class="rel-shell"><p>No se pudo cargar el listado: '+esc(e.message)+'</p><button class="btn" data-resume>Volver al borrador</button></div>';}}
  document.addEventListener('sisventas:page-changed',e=>{if(e.detail.page==='relevamientos')open();});
  document.addEventListener('input',e=>{if(!e.target.closest('#page-relevamientos')||!draft||busy)return;const n=e.target;if(n.dataset.meta)draft[n.dataset.meta]=n.value;else{const key=n.dataset.valueField||n.dataset.note;if(!key)return;const item=draft.items[key]||(draft.items[key]={});item[n.dataset.note?'note':'value']=n.value;if(n.tagName==='SELECT')item.label=n.options[n.selectedIndex].textContent;}persist();});
  document.addEventListener('change',async e=>{const n=e.target;if(!n.closest('#page-relevamientos')||!n.dataset.photo||!n.files[0]||busy)return;busy=true;renderBusy(true);try{const photo=await window.svPrepararAdjuntoImagen(n.files[0],{maxBytes:350000});const item=draft.items[n.dataset.photo]||(draft.items[n.dataset.photo]={});item.photo=photo;}catch(err){window.notify(err.message);}finally{busy=false;persist();render();}});
  document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!b.closest('#page-relevamientos')||busy)return;if(b.hasAttribute('data-resume')){open();return;}if(b.hasAttribute('data-list')){list();return;}if(!draft)return;
    if(b.dataset.step!==undefined)step=Number(b.dataset.step);else if(b.hasAttribute('data-next'))step=Math.min(3,step+1);else if(b.hasAttribute('data-back'))step=Math.max(0,step-1);else if(b.dataset.service){const s=b.dataset.service;draft.services=draft.services.includes(s)?draft.services.filter(x=>x!==s):draft.services.concat(s);persist();}else if(b.dataset.choice){const item=draft.items[b.dataset.choice]||(draft.items[b.dataset.choice]={});item.value=b.dataset.value;persist();}else if(b.dataset.delta){const key=b.dataset.key,item=draft.items[key]||(draft.items[key]={});item.value=Math.max(0,Math.min(9999,(Number(item.value)||0)+Number(b.dataset.delta)));persist();}else if(b.dataset.removePhoto){delete draft.items[b.dataset.removePhoto].photo;persist();}else if(b.hasAttribute('data-save')){save();return;}else return;const y=window.scrollY;render();window.scrollTo(0,y);
  });
})();
